# 提升 Gradle 可用内存
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Fabric / Babric 相关属性
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+e0778a3
loader_version=0.19.3

# 模组信息
mod_version=1.0.0
mod_id=memorysweep
maven_group=com.memorysweep
archives_base_name=memorysweep

# 依赖 - StationAPI (前置)
stationapi_version=2.0.0-alpha.6.2
